# Generated by Django 3.1.2 on 2020-10-23 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appusers',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='appusers',
            old_name='FirstName',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='appusers',
            old_name='LastName',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='appusers',
            old_name='Married',
            new_name='married',
        ),
    ]
